/*
 * Lifetime Immigration — static site build
 *
 * Assembles pages from src/pages/*.html into plain static HTML at the project
 * root, using src/layout.html as the shell and src/partials/*.html for the
 * shared header and footer.
 *
 * No dependencies. Run:  node build.js
 *
 * Page sources begin with a JSON block in an HTML comment:
 *
 *   <!--{ "title": "...", "description": "...", "nav": "immigrate" }-->
 *
 * `nav` marks the matching top-level nav item as current.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'src');
const OUT = __dirname;

const read = p => fs.readFileSync(p, 'utf8');

// --- load partials ---------------------------------------------------------
const partials = {};
for (const file of fs.readdirSync(path.join(SRC, 'partials'))) {
  if (file.endsWith('.html')) {
    partials[path.basename(file, '.html')] = read(path.join(SRC, 'partials', file));
  }
}

const layout = read(path.join(SRC, 'layout.html'));

// --- helpers ---------------------------------------------------------------
function parseFrontMatter(src, file) {
  const m = src.match(/^\s*<!--(\{[\s\S]*?\})-->\s*/);
  if (!m) throw new Error(`${file}: missing leading <!--{ ... }--> metadata block`);
  let meta;
  try {
    meta = JSON.parse(m[1]);
  } catch (e) {
    throw new Error(`${file}: metadata is not valid JSON — ${e.message}`);
  }
  return { meta, body: src.slice(m[0].length) };
}

function includePartials(html) {
  return html.replace(/\{\{>\s*([\w-]+)\s*\}\}/g, (_, name) => {
    if (!(name in partials)) throw new Error(`unknown partial: ${name}`);
    return partials[name];
  });
}

// Mark the current top-level nav item. Links opt in with data-nav="key".
function markCurrentNav(html, key) {
  if (!key) return html.replace(/\s*data-nav="[\w-]+"/g, '');
  return html.replace(/<a([^>]*?)data-nav="([\w-]+)"([^>]*?)>/g, (m, a, navKey, c) => {
    if (navKey !== key) return `<a${a}${c}>`;
    const withClass = /class="/.test(a + c)
      ? `<a${a}${c}>`.replace(/class="/, 'class="is-current ')
      : `<a${a}${c}>`.replace('<a', '<a class="is-current"');
    return withClass.replace('>', ' aria-current="page">');
  });
}

function fill(html, meta) {
  return html.replace(/\{\{(\w+)\}\}/g, (_, key) => {
    const v = meta[key];
    return v === undefined ? '' : String(v);
  });
}

// --- build -----------------------------------------------------------------
const pagesDir = path.join(SRC, 'pages');
const pages = fs.readdirSync(pagesDir).filter(f => f.endsWith('.html'));

let built = 0;
for (const file of pages) {
  const { meta, body } = parseFrontMatter(read(path.join(pagesDir, file)), file);

  let html = layout.replace('{{body}}', () => body);
  html = includePartials(html);
  html = fill(html, meta);
  html = markCurrentNav(html, meta.nav);

  const banner = '<!-- Generated by build.js from src/pages/' + file + ' — do not edit directly -->\n';
  fs.writeFileSync(path.join(OUT, file), banner + html);
  built++;
  console.log('  ' + file.padEnd(24) + (meta.title || '').slice(0, 58));
}

console.log(`\nBuilt ${built} page${built === 1 ? '' : 's'}.`);
